sudo: false

language: python

python:
    - "3.5"

install:
    - ./setup.sh cpu
    - pip install --user codecov

script:
    - coverage run --source . --omit main.py run_tests.py

after_success:
    - codecov
